spring.application.name=NotificationEngineNdhuvi


# Email configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=lunghani.banyini@gmail.com
#spring.mail.password=ohjnnmhhwhsbyqtb
#spring.mail.properties.mail.debutrue
##g=spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000


# H2 In-memory Database URL
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.url=jdbc:h2:mem:NotificationEngine;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE


# Hibernate dialect for H2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create/update tables
#spring.jpa.hibernate.ddl-auto=create

# Show SQL in console
#spring.jpa.show-sql=true

# Enable H2 console for web access (http://localhost:8080/h2-console)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Database configuration (Render PostgreSQL)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Render dynamic port
server.port=${PORT:8080}